services:
  postgres:
    image: postgres:15
    container_name: mealplan-postgres
    environment:
      POSTGRES_USER: pep_user
      POSTGRES_PASSWORD: pep_user
      POSTGRES_DB: mealplan
    ports:
      - "5433:5432"
    volumes:
      - mealplan_pgdata:/var/lib/postgresql/data

  backend2:
    build:
      context: ./backend/pep-mealplan-backend
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: mealplan-backend2
    ports:
      - "8081:8080"
    environment:
      QUARKUS_HTTP_HOST: "0.0.0.0"
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/mealplan"
      QUARKUS_DATASOURCE_USERNAME: "pep_user"
      QUARKUS_DATASOURCE_PASSWORD: "pep_user"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Docker/Dockerfile
    container_name: mealplan-frontend
    ports:
      - "8082:80"
    depends_on:
      - backend2

volumes:
  mealplan_pgdata:
