name: Build and Deploy Mealplan-Backend2

on:
  push:
    branches:
      - main
    paths:
      - 'pep-mealplan/backend/pep-mealplan-backend/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: pep-mealplan/backend/pep-mealplan-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: |
          ./mvnw -B clean package -DskipTests

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TEMP_GHCR_PAT }}

      - name: Find and set image tag
        run: |
          if test "${{ github.ref_name }}" = "main"; then tag="latest"; else tag="dev"; fi
          echo "IMAGE_TAG=${tag}" >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./pep-mealplan/backend/pep-mealplan-backend
          file: ./pep-mealplan/backend/pep-mealplan-backend/src/main/docker/Dockerfile.jvm
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/mealplan-backend2:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to VM (SSH)
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/stuetzadm/deploy/compose
            echo "Current working dir:"
            pwd
            echo "Content of dir:"
            ls -lah

            # Hol dir das neue Image von GHCR
            docker compose -f docker-compose.yaml pull backend2

            # Starte nur backend2 neu (DB bleibt unber√ºhrt)
            docker compose -f docker-compose.yaml up -d backend2

            docker compose -f docker-compose.yaml ps
            docker compose -f docker-compose.yaml logs --tail=80 backend2
